### PR TITLE
Reformat spacing and standardize style

### PR DESCRIPTION
**Pull request by samau3**
1. Mass reformatting of files to utilize 2 spaces for indentation
2. Added missing semicolons
3. Changed so all double quotations are single quotations (exceptions being strings that utilize an apostrophe)

### CODE REVIEW

**Comment by li-andy** [comment]
1. where are you enforcing style? 
2. why keep semicolons as opposed to omitting?

**Comment by samau3** [comment]
> where are you enforcing style?
It was mainly just switching quotes from double quotes to single quotes since before it was a mix of both being used across the file.

> why keep semicolons as opposed to omitting?
When learning Javascript I was informed by more experienced engineers to always have semicolons, and discussions online still suggest to have them over not

**Comment by li-andy** [comment]
> > where are you enforcing style?
> 
> It was mainly just switching quotes from double quotes to single quotes since before it was a mix of both being used across the file.

style should be enforced strictly via a formatter, otherwise someone (or you) can commit non-conformant code in the future

> > why keep semicolons as opposed to omitting?
> 
> When learning Javascript I was informed by more experienced engineers to always have semicolons, and discussions online still suggest to have them over not

does this rationale still apply for typescript?

**Comment by samau3** [comment]
> style should be enforced strictly via a formatter, otherwise someone (or you) can commit non-conformant code in the future

Oh, then I'll look into finding a linter/formatter that can take care of the quotes if possible. Any recommendations?

> does this rationale still apply for typescript?

Most discussions does seem to down to personal preference or adding a linter setting that handles it.

**Comment by li-andy** [comment]
> > style should be enforced strictly via a formatter, otherwise someone (or you) can commit non-conformant code in the future
> 
> Oh, then I'll look into finding a linter/formatter that can take care of the quotes if possible. Any recommendations?
> 
`prettier` should do the trick

> > does this rationale still apply for typescript?
> 
> Most discussions does seem to come down to personal preference or adding a linter setting that handles it.

back to my original question:
> why keep semicolons as opposed to omitting?

**Comment by samau3** [comment]
> why keep semicolons as opposed to omitting?

I read that it's still a best practice/good habit to keep? Other than that no deeper reasoning and am open to one way or the other.

**Comment by li-andy** [comment]
> > why keep semicolons as opposed to omitting?
> 
> I read that it's still a best practice/good habit to keep? Other than that no deeper reasoning and am open to one way or the other.

the intent of my question isn't necessarily to drive you toward some "correct" answer, but rather encourage you to make + back up an opinion 

for example, all else equal, I prefer omitting semicolons since it makes things _slightly_ easier to read with one less token

**Review by li-andy — APPROVED** [review]

**Pull request merged**
